config/routes.rb
Carpool::Application.routes.draw do
  get "fbook/new"

  get "fbook/create"

  resources :reports

  devise_for :users , :controllers => { :omniauth_callbacks => "fbook" }
  resources :cars
  resources  :users
  resource :accounts

  match "/users/admin/:id" => "users#admin"
  match "/users/promote/:id" => "users#promote"
  match "/accounts/check/:id"=> "accounts#check"
  devise_for :routs
  resources :search
  resources  :routs

  get 'accounts/list'
  get "routs/search"
  post "search/list"
  get "search/show"
  get("pages/home")
  get("pages/about")
  get("pages/contact")

  

   root :to => 'pages#home'

end

app/models/rout.rb
class Rout < ActiveRecord::Base

  acts_as_gmappable  :process_geocoding => false

  attr_accessible :description, :d_from, :d_to, :price, :travel_date,:free_seats,:user_id ,:car_id, :travel_t,:latitude,:longitude,:gmaps
   validates_presence_of :d_from, :d_to, :price, :travel_date,:free_seats

   validates :travel_t, :format => {:with => /^\(?(\d{2})\)?[: ]?(\d{2})$/}, :on => :update
  belongs_to :user
  belongs_to :car

  def self.search(search,search1,travel_date)
  if search
    find(:all, :conditions => ['d_from LIKE ? OR d_to LIKE ? OR d_to LIKE ? ', search, search1,travel_date])
  else
     scoped 
  end
end
end
  
     
        
   

app/controllers/routs_controller.rb
class RoutsController < ApplicationController
  # GET /routs
  # GET /routs.json
 
 before_filter :authenticate_user!
  #@routs = Rout.page(params[:page]).per(5)
  
  #render  'index'
  
  
    def index
     
     
    if current_user.Admin?
    @routs = Rout.paginate(:page => params[:page], :per_page => 5).order("created_at DESC")
    else
      if current_user.isDriver?
      @routs=Rout.paginate(:page => params[:page], :per_page => 5).where("user_id=?",current_user.id).order("created_at DESC")
      else
        redirect_to pages_home_path
      end
    end

  end

 
  # GET /routs/1
  # GET /routs/1.json
  def show
   # @rout = Rout.find(params[:id])
    @rout = Rout.find(params[:id],:include => :user, :joins => "INNER JOIN users ON routs.user_id = users.id")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rout }
    end
  end

  # GET /routs/new
  # GET /routs/new.json
  
  def new
    @cars =Car.where("user_id=?",current_user.id)
    @rout = Rout.new
   
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rout }
    
    
     end
    end


  # GET /routs/1/edit
  def edit
    @cars =Car.where("user_id=?",current_user.id)
    @rout = Rout.find(params[:id])
    @t_date=@rout.travel_date
  end

  # POST /routs
  # POST /routs.json
  def create


    @rout = Rout.new(params[:rout])
    @rout.travel_date=params[:travel_date].to_date

    respond_to do |format|
      if @rout.save
        format.html { redirect_to @rout, notice: 'Rout was successfully created.' }
      format.json { render json: @rout, status: :created, location: @rout }
      else
        @cars =Car.where("user_id=?",current_user.id)
        format.html { render action: "new" }
        format.json { render json: @rout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /routs/1
  # PUT /routs/1.json
  def update
    @rout = Rout.find(params[:id])

    respond_to do |format|
      if @rout.update_attributes(params[:rout])
        format.html { redirect_to @rout, notice: 'Rout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routs/1
  # DELETE /routs/1.json
  def destroy
    @rout = Rout.find(params[:id])
    @rout.destroy

    respond_to do |format|
      format.html { redirect_to routs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/routs_helper.rb
module RoutsHelper
end

app/views/routs/_form.html.erb
<%= form_for(@rout,{:class=>"form-horizontal"}) do |f| %>

  <div>
      <table  >
    <tr>
      <td><%= f.label "from",:class=>"label label-info"%></td>
      <td><%= f.select :d_from,  options_for_select(["Kabul", "Herat","Kandahar","Nangarhar","Balkh","Khost", "Sarepool"])%> </td>
    </tr>
    <tr>
     <td> <%= f.label :Destination,:class=>"label label-info"%></td>
      <td><%= f.select  :d_to, options_for_select(["Kabul", "Herat","Kandahar","Nangarhar","Balkh","Khost", "Sarepool"]) %></td>
    </tr>
    <tr class="controls">

      <td><%= f.label :"price",:class=>"label label-info" %><br /></td>
      <td><%= f.number_field :price, :class=>"inputInfo" %></td>

    </tr>
       <tr>
      <td><%= f.label :date,:class=>"label label-info" %></td>


      <td>
       <input type="text" value="<%= @t_date %>"  data-behaviour='datepicker' name="travel_date">
       
      </td>
      

    </tr>
    
    <tr>
      <td><%= f.label :free_seats ,:class=>"label label-info"%><br /></td>
      <td><%= f.number_field :free_seats, :ignore_date => true%>        </td>
    </tr>
    <tr>
      <td><%= f.label  :travel_time ,:class=>"label label-info"%><br /></td>
      <td><%= f.text_field :travel_t, :placeholder => "Enter time format as(hh:mm)"%>        </td>
    </tr>

    <tr>
     <td><%= f.label  :Car_Plate_Number ,:class=>"label label-info"%><br /></td>


      <td><%= f.collection_select(:car_id, @cars,:id, :number_plate,{:prompt => true}) %>      </td>




    </tr>
    
    <tr>
      <td><%= f.label :Descriptions ,:class=>"label label-info"%><br /></td>
      <td ><%= f.text_area :description %>        </td>
    </tr>
      <tr>
       <td><%= f.hidden_field :user_id, :value => current_user.id %>        </td>
    </tr>      
     
    
    <tr >
      <td colspan="2">&nbsp;&nbsp;&nbsp;<%= f.submit :class=>"btn btn-primary" %></td>
    </tr>
      </table>

        </div>
<% end %>

<script type="text/javascript">
    $('[data-behaviour~=datepicker]').datepicker({
        dateFormat: 'yy-mm-dd'
    })


</script>

app/views/routs/edit.html.erb
<h1>Editing rout</h1>

<%= render 'form' %>

<%= link_to 'Show', @rout %> |
<%= link_to 'Back', routs_path %>

app/views/routs/index.html.erb
<div style="height: 450px">
 
<div class="table">
	

	
  <h2>List of Routes</h2>
  <table summary="users list" class="table table-striped">
    <tr class="success">
      <th>&nbsp;</th>
      <th>Frome</th>
      <th>Destanition</th>
      <th>Price</th>
      <th>Travel Date</th>
      <th>Travel Time</th>
      
      
     
      <th colspan="3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Action</th>
    </tr>




    <%@routs.each do |rout| %>
    <tr>
      <td>&nbsp;</td>
      <td><%= rout.d_from %></td>
      <td><%= rout.d_to%></td>
      <td><%= number_to_currency(rout.price, :unit => "Afg;", :format => "%n %u") %></td>

      <td><%= rout.travel_date %></td>
      <td><%= rout.travel_t %></td>
     
      <td>


        <div class="btn-group">
          <button class="btn btn-primary">Action</button>
          <button class="btn dropdown-toggle btn-primary" data-toggle="dropdown">
            <span class="caret "></span>
          </button>
          <ul class="dropdown-menu">

            <li> <%= link_to 'Edit', edit_rout_path(rout) %></li>
            <li><%= link_to 'Destroy', rout, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            <li class="divider"></li>
            <li><%= link_to("Register New Car", new_rout_path)%></li>

          </ul>
        </div>



      </td>
    
 
    </tr>

    <% end %>
    
  </table>
  
  <%= link_to 'Create New rout', new_rout_path %>|
  
   
</div>
</div>

<%= will_paginate @routs,:previous_label=>"<<",:next_label=>">>"  %>

app/views/routs/new.html.erb
<h1>New rout</h1>

<%= render 'form' %>

<%= link_to 'Back', routs_path %>

app/views/routs/show.html.erb
<table border="2"  class="table table-striped" summary="Routs Description">
	
		
		<tr >
		<td>From:</td>	
		<td><%= @rout.d_from %></td>
		</tr>
		<tr >
		<td>Distanation:</td>
		<td> <%= @rout.d_to %></td>
		</tr>
			
		<tr>
			<td>Price:</td>
			<td><%= number_to_currency(@rout.price, :unit => "Afg;", :format => "%n %u") %></td>
			
		</tr>
		
		<tr>
			<td>Avalible Seats:</td>
			<td> <%= @rout.free_seats %></td>
		</tr>
		<tr>
			<td>Travelling Date:</td>
			<td><%= @rout.travel_date %></td>
		</tr>
		
		<tr>
			<td>Travelling Time:</td>
			<td><%= @rout.travel_t %></td>
		</tr>

		
	<tr>
		<td>Descriptions:</td>
		<td> <%= @rout.description %></td>
	</tr>
		
				

	
</table>

<%= link_to 'Edit The Rout', edit_rout_path(@rout) %> |
<%= link_to 'Back to the Routs', routs_path %>|
<%= link_to 'Delete This Rout', @rout, method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to 'Create New Rout', new_rout_path %>