config/routes.rb
Carpool::Application.routes.draw do
  get "fbook/new"

  get "fbook/create"

  resources :reports

  devise_for :users , :controllers => { :omniauth_callbacks => "fbook" }
  resources :cars
  resources  :users
  resource :accounts

  match "/users/admin/:id" => "users#admin"
  match "/users/promote/:id" => "users#promote"
  match "/accounts/check/:id"=> "accounts#check"
  devise_for :routs
  resources :search
  resources  :routs

  get 'accounts/list'
  get "routs/search"
  post "search/list"
  get "search/show"
  get("pages/home")
  get("pages/about")
  get("pages/contact")

  

   root :to => 'pages#home'

end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible :number_plate,:photo,:no_passengers,:others,:model,:company,:user_id

  belongs_to :user
  has_many :routs
  has_attached_file :photo

  has_many :report

  validates_uniqueness_of :number_plate





end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

 def index
      if current_user.Admin?
      @cars=Car.all
      else
        if current_user.isDriver?
        @cars=Car.where(:user_id => current_user.id)
        else
          redirect_to pages_home_path
          end
      end

 end

 def new
 @car=Car.new
 @car.user_id=current_user.id
 end

 def create
    @car=Car.new(params[:car])
  if @car.save
   redirect_to :action=> "index"
  else
    render :action => "new"
  end

 end

  def edit
    @car=Car.find(params[:id])
  end

  def update
    @car=Car.find(params[:id])
    if @car.update_attributes(params[:car])
      redirect_to(:action=>'index')
    else
      render 'edit'
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car,:html=> {:multipart =>true}) do |f| %>
    <div style="float: right; height: 200px; width:200px; border: 2px solid #000000; margin-right: 300px ">
      <% if @car!=nil %>
        <%= image_tag @car.photo.url %>
      <% end %>
    </div>
    <div >
      <table  >
        <tr>
          <%=f.hidden_field :user_id%>
          <td><%= f.label "Number Plate",:class=>"label label-info"%></td>
          <td><%= f.text_field :number_plate%> </td>
        </tr>
        <tr>
          <td> <%= f.label :Model, :class=>"label label-info"%></td>
          <td><%= f.number_field :model %></td>
        </tr>
        <tr class="controls">

          <td><%= f.label :"Company",:class=>"label label-info" %><br /></td>
          <td><%= f.text_field :company, :class=>"inputInfo" %></td>

        </tr>
        <tr>
          <td><%= f.label "No Passangers",:class=>"label label-info" %></td>
          <td><%= f.number_field :no_passengers %></td>
        </tr>


        <tr>
          <td><%= f.label :photo ,:class=>"label label-info"%><br /></td>
          <td><%= f.file_field :photo %>        </td>
        </tr>
        <tr>
          <td><%= f.label :Descriptions ,:class=>"label label-info"%><br /></td>
          <td><%= f.text_area :others %>        </td>
        </tr>


        <tr >
          <td colspan="2">&nbsp;&nbsp;&nbsp;<%= f.submit :class=>"btn btn-primary" %></td>
        </tr>
      </table>

    </div>
<% end %>


app/views/cars/edit.html.erb
<h3>Edit Car</h3>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<div class="table">
  <h2>User Cars</h2>
  <table summary="users list" class="table table-striped">
    <tr class="success">
      <th>&nbsp;</th>
      <th>Number Plate</th>
      <th>Model</th>
      <th>Company</th>

      <th>Number Passengers</th>
      <th>Description</th>

      <th colspan="3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Action</th>
    </tr>





    <% @cars.each do |car| %>
        <tr>
          <td>&nbsp;</td>
          <td><%= car.number_plate %></td>
          <td><%= car.model%></td>
          <td><%= car.company %></td>

          <td><%= car.no_passengers %></td>
          <td><%= car.others %></td>
          <td>
          <div class="btn-group">
            <button class="btn btn-primary">Action</button>
            <button class="btn dropdown-toggle btn-primary" data-toggle="dropdown">
              <span class="caret "></span>
            </button>
            <ul class="dropdown-menu">

              <li> <%= link_to 'Edit', edit_car_path(car) %></li>
              <li><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <li class="divider"></li>
              <li><%= link_to("Register New Car", new_car_path)%></li>
              <li><%= link_to 'Show', car %></li>
            </ul>
          </div>




          </td>




        </tr>

    <% end %>

  </table>

  <%= link_to 'Register New Car', new_car_path %>

  </div>

app/views/cars/new.html.erb
<h3>Register Car</h3>

<%= render 'form' %>



<%= link_to 'Back', cars_path %>