config/routes.rb
Carpool::Application.routes.draw do
  get "fbook/new"

  get "fbook/create"

  resources :reports

  devise_for :users , :controllers => { :omniauth_callbacks => "fbook" }
  resources :cars
  resources  :users
  resource :accounts

  match "/users/admin/:id" => "users#admin"
  match "/users/promote/:id" => "users#promote"
  match "/accounts/check/:id"=> "accounts#check"
  devise_for :routs
  resources :search
  resources  :routs

  get 'accounts/list'
  get "routs/search"
  post "search/list"
  get "search/show"
  get("pages/home")
  get("pages/about")
  get("pages/contact")

  

   root :to => 'pages#home'

end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :car_number_plate, :driver_lastname, :driver_name, :report_body, :travel_date, :travel_from, :travel_time, :travel_to
  belongs_to :car
  
  def self.search(search)
  if search
    find(:all, :conditions => ['driver_name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    
    @reports = Report.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report,{:class=>"form-horizontal"}) do |f| %>

  <div>
      <table calss='table' >    	
    
    <tr>
      <td><%= f.label :driver_name,:class=>"label label-info"%></td>
      <td><%= f.text_field :driver_name %> </td>
    </tr>
     <tr>
      <td><%= f.label :driver_lastname,:class=>"label label-info"%></td>
      <td> <%= f.text_field :driver_lastname %> </td>
    </tr>
    <tr>
      <td><%= f.label :travel_from,:class=>"label label-info"%></td>
      <td><%= f.select :travel_from,  options_for_select(["Kabul", "Herat","Kandahar","Nangarhar","Balkh", "Sarepool"])%> </td>
    </tr>
    <tr>
     <td> <%= f.label :travel_to,:class=>"label label-info"%></td>
      <td><%= f.select  :travel_to, options_for_select(["Kabul", "Herat","Kandahar","Nangarhar","Balkh", "Sarepool"]) %></td>
    </tr>
    <tr>    

      <td><%= f.label :car_number_plate, :class=>"label label-info" %><br /></td>
      <td><%= collection_select(:post, :car_number_plate, Car.all, :id,:number_plate ) %> </td>

    </tr>
       <tr>
      <td><%= f.label :date,:class=>"label label-info" %></td>


      <td>
       <input type="text" value="<%= @t_date %>"  data-behaviour='datepicker' name="travel_date">
      </td>

    </tr>
    <tr>
      <td><%= f.label  :travel_time ,:class=>"label label-info"%><br /></td>
      <td><%= f.text_field :travel_time, :placeholder => "Enter time format as(hh:mm)"%>        </td>
    </tr>
      <tr>
      <td><%= f.label :Write_your_report ,:class=>"label label-info"%><br /></td>
      <td ><%= f.text_area :report_body , :cols=>1,:rows=>5 %>        </td>
    </tr>
      
     
    
    <tr >
      <td colspan="2">&nbsp;&nbsp;&nbsp;<%= f.submit :class=>"btn btn-primary" %></td>
    </tr>
      </table>

        </div>
<% end %>

<script type="text/javascript">
    $('[data-behaviour~=datepicker]').datepicker({
        dateFormat: 'yy-mm-dd'
    })
</script>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<%= form_tag reports_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], :placeholder => "Enter the name of the drive " %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table class="table">
  <tr>
    <th>Driver name</th>
    <th>Driver lastname</th>
    <th>Car number plate</th>
    <th>Travel date</th>
    <th>Travel time</th>
    <th>Report body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.driver_name %></td>
    <td><%= report.driver_lastname %></td>
    <td><%= report.car_number_plate %></td>
        <td><%= report.travel_date %></td>
    <td><%= report.travel_time %></td>
    <td><%= "can be seen in previews" %></td>
    <td><%= link_to 'Show', report %></td>
    <td><%= link_to 'Edit', edit_report_path(report) %></td>
    <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Driver name:</b>
  <%= @report.driver_name %>
</p>

<p>
  <b>Driver lastname:</b>
  <%= @report.driver_lastname %>
</p>

<p>
  <b>Car number plate:</b>
  <%= @report.car_number_plate %>
</p>

<p>
  <b>Travel from:</b>
  <%= @report.travel_from %>
</p>

<p>
  <b>Travel to:</b>
  <%= @report.travel_to %>
</p>

<p>
  <b>Travel date:</b>
  <%= @report.travel_date %>
</p>

<p>
  <b>Travel time:</b>
  <%= @report.travel_time %>
</p>

<p>
  <b>Report body:</b>
  <%= @report.report_body %>
</p>


<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>