config/routes.rb
Carpool::Application.routes.draw do
  get "fbook/new"

  get "fbook/create"

  resources :reports

  devise_for :users , :controllers => { :omniauth_callbacks => "fbook" }
  resources :cars
  resources  :users
  resource :accounts

  match "/users/admin/:id" => "users#admin"
  match "/users/promote/:id" => "users#promote"
  match "/accounts/check/:id"=> "accounts#check"
  devise_for :routs
  resources :search
  resources  :routs

  get 'accounts/list'
  get "routs/search"
  post "search/list"
  get "search/show"
  get("pages/home")
  get("pages/about")
  get("pages/contact")

  

   root :to => 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carpool</title>
  <%= stylesheet_link_tag    "application","main.css", :media => "all" %>

  <%= javascript_include_tag "application","main.js" %>
  <%= stylesheet_link_tag("application","datepicker.css") %>
  <script src="/javascripts/jquery.js" type="text/javascript"></script>
  <script src="/javascripts/jquery.ui.datepicker.js"></script>

  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>

<div class="navbar navbar-inverse">
  <div class="navbar-inner nav-collapse" style="height: auto;">
    <div class="container">

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>


      <!-- Menu of the page -->




     <a class="brand" href="#"><span style="color:red; background-image: url( '<%= asset_path 'flag.png' %>') ">CARPOOL</span><span style="color: green">AFGHANISTAN</span></a>

      <ul class="nav">

          <li><%= link_to("HOME", pages_home_path)%> </li>
     

        <li><%= link_to 'SEARCH',   search_index_path  %></li>
       
        <li><%= link_to("ABOUT US", pages_about_path)%></li>
        
        <li><%= link_to("CONTACT", pages_contact_path)%></li>
        <% if user_signed_in? %>

                <li><%= link_to "PROFILE",users_path %></li>

            <% end %>


         
        <li>    <% if user_signed_in? %>

              <%= link_to 'SIGN OUT', destroy_user_session_path, :method => 'delete' %>
          <% else %>
              <%= link_to 'SIGN IN', new_user_session_path  %>
            <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
              </li>
              <li>
              <%= link_to 'SIGN UP',  new_user_registration_path  %></li>
          <% end %>

         <li> <% if user_signed_in? %>
               <% if current_user.Admin? || current_user.isDriver? %>
          <div class="btn-group">
            <button class="btn ">Account Management</button>
            <button class="btn dropdown-toggle " data-toggle="dropdown">
              <span class="caret "></span>
            </button>
            <ul class="dropdown-menu">

              <li><%= link_to("Your Routes Info",routs_path,:class => "action edit") %></li>
              <li><%= link_to 'Your Cars Info', cars_path %></li>

              <li class="divider"></li>
              <li><%= link_to("Profile Management",users_path,:class => "action edit") %></li>
              <% if current_user.Admin? %>

              <li><%= link_to "Accounts Request",accounts_path%></li>
              <% end %>

            </ul>
          </div>
                <% end %>
               <% end %>
               </li>


      </ul>



    </div>
  </div>
</div>
<!-- End of Navbar -->

<div class="Nav-left">
	
	<%= link_to(image_tag("r-b.jpg") , new_report_path)%><br />
	
	 
	</div>
<div class="Nav-right">
	<%= image_tag("r-nav.jpg")%>
	
	</div>
<!--Start of the body of the page -->

<div class="container">
  <div class="row-fluid">
    <div class="span12">

      <!-- ===================================== LOCALIZATION ===================================== -->






      <!-- ===================================== PICTURE SLIDES ===================================== -->


        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      <div style="height: 200px">
      <%= yield :scripts %>

        </div>
    </div>


</div>
</div>









<!-- ===================================== MEET TEAM ===================================== -->


<div class="navbar navbar-inverse navbar-bottom">
  <div class="navbar-inner">
    <div class="container">



      









      <br/>
      <br/>







     
     
      <!--End -->

      <!-- ===================================== START FOOTER ===================================== -->
      
      <div >
        &copy; Copyright 2013 All Rights Reserved. The
        <a href="http://www.carpoolafghanistan.com">Carpool AFGHANISTAN</a> ¥
        build by team of:
        <a href="https://www.facebook.com/groups/131081877082483/">Afghan Student at TU Berlin</a>
      </div>
 
    </div>
  </div>
</div>









<script>
    $(document).ready(function(){
        $('.carousel').carousel();
    });
</script>

<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"%>
<script>window.jQuery || document.write('<script src="js/jquery-1.7.2.min.js"><\/script>')</script>


<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"%>
<%= javascript_include_tag "/twitter-bootstrap/twitter-bootstrap-v2/js/bootstrap-modal.js"%>

<%= javascript_include_tag "http://code.jquery.com/jquery.js" %>
<%= javascript_include_tag"https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"  %>
<%=  javascript_include_tag 'bootstrap.min.js' %>
<%= javascript_include_tag 'bootstrap.js'%>





</body>
</html>